config/routes.rb
Zoorail::Application.routes.draw do
  get "profiles/show"
  devise_for :users
  
  devise_scope :user do 
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end
  
  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index' 
  get 'gallery_1', to: 'statuses#gallery_1'
  get 'gallery_2', to: 'statuses#gallery_2'
  get 'gallery_3', to: 'statuses#gallery_3'
  get 'gallery_4', to: 'statuses#gallery_4'
  get 'gallery_5', to: 'statuses#gallery_5' 
  get 'gallery_6', to: 'statuses#gallery_6' 
  get 'about', to: 'statuses#about'
  
  get '/:id', to: 'profiles#show'
  
  
  

  

end

app/models/status.rb
class Status < ActiveRecord::Base
  
  belongs_to :user
  
  validates :content, presence: true,
                      length: { minimum: 2 }
  
  validates :user_id, presence: true
 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  
  validates :profile_name, presence: true, 
                            uniqueness: true,
                            format: { 
                              with: 
                              /\A[a-zA-Z0-9_-]+\Z/,
                              message: 'must be formatted correctly'
                              }
  
  has_many :statuses
  
  def full_name
    first_name + " " + last_name
  end  
  
  def gravatar_url
    stripped_email = email.strip
    downcased_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)
    
    "http://gravatar.com/avatar/#{hash}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  protected

  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super # Use the default one
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_profile_name(params[:id])
    if @user
      @statuses = @user.statuses.all
      render action: :show
    else
      render file: 'public/404', status: 404, formats:[:html]
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

  # Never trust parameters from the scary internet, only allow the white list through.
  #NF edit: replaces attr_accessible from status.rb model....
    def status_params
      params.require(:status).permit(:content, :user_id)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(type)
    case type
    when :alert
      "alert-danger"
    when :notice
      "alert-success"
    else 
      ""
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper

end

app/views/galleries/gallery1.html.erb
<div class="page-header">
  <h2>Welcome to StencilZoo!</h2>
</div>
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img data-src="holder.js/300x200" alt="...">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_gallery_header.html.erb
<div class="page-header">
</div>

<!-- Sample Image Thumbnail with lightbox functionality
  <div class="col-xs-6 col-sm-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag("gallery/****.png", :class => "img-responsive", :alt => "...") %>
      <div class="caption">
        <h3>Image Label</h3>
        <p>...and description...wxh</p>
        <p><a href="/assets/gallery/****.png" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
-->

app/views/layouts/_gallery_pagination.html.erb
<div class="text-center">
  <ul class="pagination pagination-lg">
    
    <%= nav_link_to '1', gallery_1_path, {:class => ''}, {:wrapper => 'li', :selected_class => 'active'} %>
    <%= nav_link_to '2', gallery_2_path, {:class => ''}, {:wrapper => 'li', :selected_class => 'active'} %>
    <%= nav_link_to '3', gallery_3_path, {:class => ''}, {:wrapper => 'li', :selected_class => 'active'} %>
    <%= nav_link_to '4', gallery_4_path, {:class => ''}, {:wrapper => 'li', :selected_class => 'active'} %>
    <%= nav_link_to '5', gallery_5_path, {:class => ''}, {:wrapper => 'li', :selected_class => 'active'} %>
    <%= nav_link_to '6', gallery_6_path, {:class => ''}, {:wrapper => 'li', :selected_class => 'active'} %>
    
  </ul>
</div>

<!--
boostrap pagination:
<ul class="pagination">
  <li class="disabled"><a href="#">&laquo;</a></li>
  <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
  ...
</ul>

Nav Lynx with wrapper div:
nav_link_to 'Page', some_page_path, {:class => 'link'}, {:wrapper => 'li', :wrapper_class => 'test-wrapper', 
  :selected_class => 'active'}
Outputs:
<li class="active test-wrapper"><a href="example.com/page" class="link">Page</a></li>
-->

app/views/layouts/_galleryheader.html.erb
<div class="page-header">
  <h2>The Gallery  <small>A collection of my favorite art pieces</small></h2>
</div>

<!-- Sample Image Thumbnail with lightbox functionality
  <div class="col-xs-6 col-sm-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag("gallery/****.png", :class => "img-responsive", :alt => "...") %>
      <div class="caption">
        <h3>Image Label</h3>
        <p>...and description...wxh</p>
        <p><a href="/assets/gallery/****.png" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>StencilZoo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" %>
</head>
<body class="background">
  <nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        
            <!-- logo added here -->
        <%= link_to(image_tag("stencilzoo_black.png", :alt => "logo", :class => "navbar-brand logo"), "/") %>
        <a href="/" class="navbar-brand"></a>
      </div>
      
         <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <!-- removed =  -->
          <li><% link_to "All Statuses", feed_path %></li>
          <li><%= link_to "Tumblr/Blog", "http://stencilzoo.tumblr.com/" %></li>
          <li><%= link_to "Gallery", gallery_1_path %></li>
          <li><%= link_to "About", about_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.full_name, edit_user_registration_path %></li>
            <li><%= link_to "Log Out", logout_path %></li>            
          <% else %>
            <li><% link_to "Register", register_path %></li>
            <li><% link_to "Log In", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  
  <div class="container">
    <% flash.each do |type, message| %>
      <div class="alert <%= flash_class type %>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= message %>
      </div>
    <% end %>
    
    <%= yield %>
  </div>
  <div class="navbar navbar-static-bottom">
    <div class="container footer">
        <p>Copyright 2013 StencilZoo.com</p>
    </div>
  </div>
  <!-- LightBox -->
  <script src="https://code.jquery.com/jquery-1.6.2.min.js"></script>
  <script>
  jQuery(document).ready(function($) {
      $('.lightbox_trigger').click(function(e) {
          //prevent default action (hyperlink)
          e.preventDefault();
          //Get clicked link href
          var image_href = $(this).attr("href");
          /*
          If the lightbox window HTML already exists in document,
          change the img src to to match the href of whatever link was clicked
          If the lightbox window HTML doesn't exists, create it and insert it.
          (This will only happen the first time around)
          */
          if ($('#lightbox').length > 0) { // #lightbox exists
              //place href as img src value
              $('#content').html('<img src="' + image_href + '" />');
              //show lightbox window - you could use .show('fast') for a transition
              $('#lightbox').show();
          }
          else { //#lightbox does not exist - create and insert (runs 1st time only)
              //create HTML markup for lightbox window
              var lightbox =
              '<div id="lightbox">' +
                  '<p>Click to close</p>' +
                  '<div id="content">' + //insert clicked link's href into img src
                      '<img src="' + image_href +'" />' +
                  '</div>' +
              '</div>';
              //insert lightbox HTML into page
              $('body').append(lightbox);
          }
      });
      //Click anywhere on the page to get rid of lightbox window
      $('#lightbox').live('click', function() { //must use live, as the lightbox element is inserted into the DOM
          $('#lightbox').hide();
      });
  });
  </script>
</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
  <h1><%= @user.full_name %></h1>
</div>

<% if @statuses %>
  <% @statuses.each do |status| %>
    <div class="well">
      <%= status.content %>
      hi
      <hr />
      <%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago 
    </div>
  <% end %>
<% end %>
 

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.input :user_id, collection: User.all, label_method: :full_name %>
  <%= f.input :content %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/about.html.erb
<div class="page-header"></div>

<div class="jumbotron">
  <h1>Coming Soon!</h1>
  <p><span class="glyphicon glyphicon-asterisk"></span> Feel free to email 
    <a href="mailto:nick@stencilzoo.com">nick@stencilzoo.com</a> with comments, questions, concerns, praise, 
    complaints, or anything that's on your mind.</p>  
</div>

app/views/statuses/all_statuses.html.erb
<div class="page-header">
  <h1>All Statues</h1>
</div>

<!-- *** Be sure to double check Boostrap upgrades before implementing
      btn, span, etc. *** -->
<%= link_to "Post a New Status", new_status_path, class: "btn btn-success" %>

<% @statuses.each do |status| %>
<div class="status">
  <div class="row">
     <div class="span1">
       <%= image_tag status.user.gravatar_url %>
     </div>
     <div class="span7">
      <strong><%= status.user.full_name %></strong>
      <p><%= status.content %></p>
      <div class="meta">
        <%= link_to time_ago_in_words(status.created_at) +" ago", status %>
        <span class="admin">
          | <%= link_to "Edit", edit_status_path(status) %> |
          <%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure you want to delete this status?"}  %>
        </span>
      </div>
    </div>
  </div>
</div>  
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/gallery1.html.erb
<div class="page-header">
  <h2>The Gallery  <small>A collection of my favorite art pieces</small></h2>
</div>

<!-- Sample Image Thumbnail with lightbox functionality
  <div class="col-xs-6 col-sm-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag("gallery/****.png", :class => "img-responsive", :alt => "...") %>
      <div class="caption">
        <h3>Image Label</h3>
        <p>...and description...wxh</p>
        <p><a href="/assets/gallery/****.png" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
-->

<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-6">
    <div class="thumbnail">
      <%= image_tag("gallery/lichspray.jpg", :class => "img-responsive", :alt => "lichspray") %>
      <div class="caption">
        <h3>Lichtenstein Remix</h3>
        <p>Spray Paint on 18"x14" Wood Panel</p>
        <p>Credits: Spray Can, Roy Lichtenstein</p>
        <p><a href="/assets/gallery/lichspray.jpg" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-6">
    <div class="thumbnail">
      <%= image_tag("gallery/losttape.jpg", :class => "img-responsive", :alt => "losttape") %>
      <div class="caption">
        <h3>Lost in the Mix</h3>
        <p>Markers on 24"x18" Black Canvas</p>
        <p>Credits: Stencil1</p>
        <p><a href="/assets/gallery/losttape.jpg" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
</div>
<div class="text-center">
  <ul class="pagination pagination-lg">
    <li><a href="#">&laquo;</a></li>
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li><a href="#">&raquo;</a></li>
  </ul>
</div>
<div class="row">
  <div class="col-xs-6 col-sm-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag("gallery/koi1.jpg", :class => "img-responsive", :alt => "koi1") %>
      <div class="caption">
        <h3>Koi #1</h3>
        <p>Spray Paint on 20"x24" Wood Panel</p>
        <p>Credits: The Stencil Library</p>
        <p><a href="/assets/gallery/koi1.jpg" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
  <div class="col-xs-6 col-sm-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag("gallery/calavera1.jpg", :class => "img-responsive", :alt => "calavera1") %>
      <div class="caption">
        <h3>Skull and Rose</h3>
        <p>Spray Paint on 11"x14" Black Canvas</p>
        <p>Credits: Stencil1</p>
        <p><a href="/assets/gallery/calavera1.jpg" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
  <div class="col-xs-6 col-sm-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag("gallery/koi2.jpg", :class => "img-responsive", :alt => "koi2") %>
      <div class="caption">
        <h3>Koi #2</h3>
        <p>Spray Paint & Markers on 20"x24" Wood Panel</p>
        <p>Credits: The Stencil Library</p>
        <p><a href="/assets/gallery/koi2.jpg" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-6">
    <div class="thumbnail">
      <%= image_tag("gallery/robotrock.jpg", :class => "img-responsive", :alt => "robotrock") %>
      <div class="caption">
        <h3>Robot Rock</h3>
        <p>Spray Paint and Markers on 24"x12" Canvas</p>
        <p>Credits: Daft Punk</p>
        <p><a href="/assets/gallery/robotrock.jpg" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-6">
    <div class="thumbnail">
      <%= image_tag("gallery/risingdragons.jpg", :class => "img-responsive", :alt => "risingdragons") %>
      <div class="caption">
        <h3>Rising Dragons</h3>
        <p>Spray Paint and Markers on 36"x12" Canvas</p>
        <p>Credits: The Stencil Library</p>
        <p><a href="/assets/gallery/risingdragons.jpg" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-6 col-sm-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag("gallery/drips1.jpg", :class => "img-responsive", :alt => "drips1") %>
      <div class="caption">
        <h3>Drips #1</h3>
        <p>Spray Paint and Markers on 16"x18" Canvas</p>
        <p><a href="/assets/gallery/drips1.jpg" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
  <div class="col-xs-6 col-sm-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag("gallery/cheese.jpg", :class => "img-responsive lightbox_trigger", :alt => "cheese") %>
      <div class="caption">
        <h3>Cheese!</h3>
        <p>Markers on 10"x10" Wood Panel</p>
        <p>Credits: Stencil1</p>
        <p><a href="/assets/gallery/cheese.jpg" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
  <div class="col-xs-6 col-sm-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag("gallery/houndstooth1.jpg", :class => "img-responsive", :alt => "houndstooth1") %>
      <div class="caption">
        <h3>Houndstooth #1</h3>
        <p>Acrylic Paint and Markers on Wood Panel</p>
        <p>Credits: Stencil1</p>
        <p><a href="/assets/gallery/houndstooth1.jpg" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-6">
    <div class="thumbnail">
      <%= image_tag("gallery/dreamtag.jpg", :class => "img-responsive", :alt => "dreamtag") %>
      <div class="caption">
        <h3>Dream Tag</h3>
        <p>Spray Paint and Markers on 30"x24" Canvas</p>
        <p><a href="/assets/gallery/dreamtag.jpg" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-6">
    <div class="thumbnail">
      <%= image_tag("gallery/elephants1.jpg", :class => "img-responsive", :alt => "elephants1") %>
      <div class="caption">
        <h3>Elephant Charms</h3>
        <p>Spray Paint on 20"x10" Canvas</p>
        <p>Credits: The Stencil Library</p>
        <p><a href="/assets/gallery/elephants1.jpg" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-6 col-sm-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag("gallery/tigerhead.jpg", :class => "img-responsive", :alt => "tigerhead") %>
      <div class="caption">
        <h3>Wild Cat!</h3>
        <p>Spray Paint on 16"x12" Wood Panel</p>
        <p><a href="/assets/gallery/tigerhead.jpg" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
</div>

app/views/statuses/gallery_1.html.erb
<div class="page-header">
  <h2>The Gallery  <small>A collection of my favorite art pieces</small></h2>
</div>

<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-6">
    <div class="thumbnail">
      <%= image_tag("gallery/lichspray.jpg", :class => "img-responsive", :alt => "lichspray") %>
      <div class="caption">
        <h3>Lichtenstein Remix</h3>
        <p>Spray Paint on 18"x14" Wood Panel</p>
        <p>Credits: Spray Can, Roy Lichtenstein</p>
        <p><a href="/assets/gallery/lichspray.jpg" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-6">
    <div class="thumbnail">
      <%= image_tag("gallery/losttape.jpg", :class => "img-responsive", :alt => "losttape") %>
      <div class="caption">
        <h3>Lost in the Mix</h3>
        <p>Markers on 24"x18" Black Canvas</p>
        <p>Credits: Stencil1</p>
        <p><a href="/assets/gallery/losttape.jpg" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
</div>

<%= render 'layouts/gallery_pagination' %>

app/views/statuses/gallery_2.html.erb
<%= render 'layouts/gallery_header' %>

<div class="row">
  <div class="col-xs-6 col-sm-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag("gallery/koi1.jpg", :class => "img-responsive", :alt => "koi1") %>
      <div class="caption">
        <h3>Koi #1</h3>
        <p>Spray Paint on 20"x24" Wood Panel</p>
        <p>Credits: The Stencil Library</p>
        <p><a href="/assets/gallery/koi1.jpg" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
  <div class="col-xs-6 col-sm-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag("gallery/calavera1.jpg", :class => "img-responsive", :alt => "calavera1") %>
      <div class="caption">
        <h3>Skull and Rose</h3>
        <p>Spray Paint on 11"x14" Black Canvas</p>
        <p>Credits: Stencil1</p>
        <p><a href="/assets/gallery/calavera1.jpg" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
  <div class="col-xs-6 col-sm-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag("gallery/koi2.jpg", :class => "img-responsive", :alt => "koi2") %>
      <div class="caption">
        <h3>Koi #2</h3>
        <p>Spray Paint & Markers on 20"x24" Wood Panel</p>
        <p>Credits: The Stencil Library</p>
        <p><a href="/assets/gallery/koi2.jpg" class="btn btn-default lightbox_trigger" role="button">
          <span class="glyphicon glyphicon-fullscreen"></span> Full View</a></p>
      </div>
    </div>
  </div>
</div>

<%= render 'layouts/gallery_pagination' %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.user.full_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>